### ISSUE TITLE
Check if MX is catchall

### ISSUE THREAD

**Issue by niravmehta** [zigbang/zigbang-email-verifier#1]
First of all, great module! Been looking for something like this.

One feature request: 

Can you also check if the MX is a catchall? A catchall MX will accept any username in RCPT TO. 

So we can do an additional RCPT TO, for randomuser@thesamedomain.tld after https://github.com/zigbang/zigbang-email-verifier/blob/master/index.js#L97 

If the MX responds with 250 for that too, we can safely assume it's a catchall - and return a slightly different success message - e.g. CATCHALL. If  MX returns 550 for this new address, it's not a catchall and we can continue returning EXISTS.

Can you add this? TIA!

**Comment by yunjunseokzb** [comment]
Thank you your request!

I will add this feature.

**Comment by niravmehta** [comment]
Awesome! Thanks.

Two node packages that may help in generating random string for username: 

- [randomstring](https://www.npmjs.com/package/randomstring)
- [Chance](https://www.npmjs.com/package/chance)
