### ISSUE TITLE
VERIFY_TIMEOUT

### ISSUE THREAD

**Issue by vnshgrg** [zigbang/zigbang-email-verifier#8]
it worked fine at first then after few requests it now responds with "VERIFY_TIMEOUT" every time.

**Comment by ygpark80** [comment]
Can you tell me what options you used? And also can you verify that the test cases pass?

e.g.
`DEBUG=email-verifier,smtp yarn test`

**Comment by vnshgrg** [comment]
`const result = await verify.verify({
                helo: "respectinc.net",
                from: "info@respectinc.net",
                to: email,
                catchalltest: true, // default false
                timeout: 5000 // default 5000
            });`

this is the options that I passed.

**Comment by ygpark80** [comment]
`VERIFY_TIMEOUT` means that the operation couldn't be verified within the specified timeout which in this case 5000 ms (5 sec). I would probably increase the timeout to something like 30 * 1000 (30 sec). If it still times out then I would recommend you turn on the debug option (e.g. DEBUG=smtp) and let me know how it behaves.

It'll show something like:
```
  smtp || connect +0ms
  smtp << 220 inbound-smtp.us-west-2.amazonaws.com ESMTP Amazon SES M1xe9oEwINWpRS1VoefG +1s
  smtp >> HELO respectinc.net +1ms
  smtp << 250 inbound-smtp.us-west-2.amazonaws.com +183ms
  smtp >> MAIL FROM: <info@respectinc.net> +0ms
  smtp << 250 Ok +163ms
  smtp >> RCPT TO: <info@respectinc.net> +1ms
```

**Comment by ygpark80** [comment]
Where are you running this program? Does it have a slow internet connection?

**Comment by vnshgrg** [comment]
I am running the program on an AWS EC2 instance so internet speed should not be the problem.

I am increasing the timeout time but I am not sure how to run DEBUG=smtp

**Comment by ygpark80** [comment]
```
$ DEBUG=smtp yarn test
```

is similar as doing

```
$ export DEBUG=smtp
$ yarn test
```

but DEBUG=smtp will only applied once. Let me know if you get the logs!
But I think increasing the timeout will fix the problem.

**Comment by vnshgrg** [comment]
Thanks, will do the smtp debug.

I increased timeout value to 60000 = 1 minute but still failing with VERIFY_TIMEOUT

let me get the smtp debug. What if I do not have yarn installed?

**Comment by ygpark80** [comment]
`DEBUG=smtp npm run test` is the same command.

**Comment by ygpark80** [comment]
`DEBUG=smtp <execute your program>`

**Comment by vnshgrg** [comment]
`
verifying smtp ping...
  smtp || connect +0ms
Error at verifyEmailSMTP VERIFY_TIMEOUT
`
debugging shows this. I think it's the SMTP connection that is failing.

**Comment by ygpark80** [comment]
Hmm very strange. Changing the first test case to something like this passes on my machine.
Do you have some sort of a firewall that blocks outgoing packets?

```
	@test("EXIST")
	async valid() {
		const host = "respectinc.net"
		const result = await verify({
			helo: host,
			from: `info@respectinc.net`,
			to: `info@respectinc.net`
		})
		expect(result).toBe('EXIST')
	}
```

**Comment by ygpark80** [comment]
Either way, does our test cases (`npm run test`) work on your machine or server?

**Comment by vnshgrg** [comment]
hmm, I changed my `from` value in the options field to my gmail address. It worked fine with my local machine but does not run on my server. Which is strange.
I don't think there is any port blocked for outgoing request. Checking it now.

**Comment by ygpark80** [comment]
SMTP uses port 22 so 22 should be open. However, I see `smtp || connect +0ms` in your log so I think connection isn't the problem. If you can provide me with some working code to reproduce your issue, I'll take a look a bit further.

**Comment by vnshgrg** [comment]
@ygpark80 
I talked to the AWS support and turned out that my smtp port was throttled by AWS. I filled up a form quickly to disable the throttle and is now working fine.

However, when i try to validate any microsoft emails such as outlook or office365 integrated email. I am getting "NOT_EXIST" even though I am sure the email exists. also the SMTP log shows 
`smtp << 550 5.7.1 Service unavailable, Client host [44.231.75.211] blocked using Spamhaus. To request removal from this list see https://www.spamhaus.org/query/ip/44.231.75.211 AS(1440) [PU1APC01FT031.eop-APC01.prod.protection.outlook.com]`
following message. Should I follow the link and request for removal as stated in the log?

Anyways, I really appreciate your effort on helping me with this case. I was really reluctant to get a email validator API service (which was a little expensive). I hope this will be sufficient for now.

Once again, thank you very much.

**Comment by ygpark80** [comment]
Glad you figured out the issue. :)

As for the spam issue, this happened to me as well and it's really up to you. Our production server that uses this module will be less repetitive compared to when developing a module and thus it will less likely to be blocked so I just ignored the issue. I think in my case this happened when I repeatedly queried non-existing email addresses.

However, if I think about it, maybe this module should instead return something like 'CANNOT_VERIFY'. Let me know or send me a PR!
